# Module: Credit M11 — Unexpected Loss & Credit VaR
# Purpose:  A stylised one-factor Monte Carlo credit-portfolio simulation, in
#           the spirit of the original CreditMetrics (JPMorgan, 1997) model
#           but stripped to its pedagogical core. The portfolio is 100
#           homogeneous obligors; each obligor's asset return is generated by
#           a single common (systemic) factor Z plus an idiosyncratic factor
#           Z_i, weighted by sqrt(rho) and sqrt(1 - rho) respectively, so the
#           pairwise asset correlation is exactly rho. An obligor defaults
#           when its asset return falls below the default boundary
#           Phi^{-1}(PD); the loss for the scenario is LGD * EAD summed
#           across defaulters. The script reports the expected loss (mean of
#           the loss vector), unexpected loss (std deviation), and the 95th,
#           99th, and 99.9th percentile of the loss distribution — the
#           Credit VaRs at the three conventional confidence levels. It then
#           re-runs the simulation at rho = 0.05 (low correlation, near-
#           normal portfolio loss) and rho = 0.50 (high correlation, fat
#           tail) to make visible the dominant role of correlation in the
#           tail.
# Caveat:   This is a *default-only* model — defaults either happen or do
#           not in the one-year horizon, and recovery is a deterministic
#           LGD. Production CreditMetrics models the joint distribution of
#           rating *migrations* (a bond that migrates from A to BBB without
#           defaulting still produces a market-value loss); the migration
#           model is a multi-state extension of the threshold logic below.
#           The script is also single-factor; production models use a 5-50
#           factor correlation matrix calibrated to industry and region
#           buckets. The point of this script is to show the *shape* of the
#           portfolio loss distribution and how it changes with correlation,
#           not to produce a regulatorily defensible Credit VaR.
# Depends:  Python 3.11+, numpy only.
# Run:      python docs/code-samples/python/c11-portfolio-sim.py

from __future__ import annotations

import math
from dataclasses import dataclass

import numpy as np


@dataclass(frozen=True)
class HomogeneousPortfolio:
    """A portfolio of identical obligors for the one-factor simulation."""

    n_obligors: int
    pd: float           # 1-year PD per obligor as decimal
    lgd: float          # LGD per obligor as decimal
    ead_usd: float      # EAD per obligor in dollars
    rho: float          # one-factor asset correlation

    @property
    def total_ead(self) -> float:
        return self.n_obligors * self.ead_usd


def simulate_portfolio_losses(portfolio: HomogeneousPortfolio,
                              n_scenarios: int,
                              seed: int = 42) -> np.ndarray:
    """Simulate the portfolio loss distribution via the one-factor model.

    The model:
        A_i = sqrt(rho) * Z + sqrt(1 - rho) * Z_i,   Z, Z_i ~ N(0, 1) i.i.d.

    Each obligor defaults when A_i <= Phi^{-1}(PD); equivalently when
    Z_i <= (Phi^{-1}(PD) - sqrt(rho) * Z) / sqrt(1 - rho). The loss in
    scenario s is LGD * EAD * (number of defaulters in s).

    Returns a vector of length n_scenarios giving the portfolio loss in
    dollars per scenario.
    """
    rng = np.random.default_rng(seed)
    # Default boundary: a standard-normal quantile at probability PD.
    default_boundary = _norm_ppf(portfolio.pd)
    # Common systemic factor, one draw per scenario.
    z_common = rng.standard_normal(size=n_scenarios)
    # Idiosyncratic factors, one draw per (obligor, scenario).
    z_idio = rng.standard_normal(size=(n_scenarios, portfolio.n_obligors))
    # Asset returns under the one-factor model.
    sqrt_rho = math.sqrt(portfolio.rho)
    sqrt_1mrho = math.sqrt(1.0 - portfolio.rho)
    # Broadcast: (n_scenarios, 1) + (n_scenarios, n_obligors) = (n_scenarios, n_obligors).
    asset_returns = sqrt_rho * z_common[:, None] + sqrt_1mrho * z_idio
    # Default indicator per (scenario, obligor).
    defaults = asset_returns <= default_boundary
    # Number of defaulters per scenario.
    n_defaults_per_scenario = defaults.sum(axis=1)
    # Dollar loss per scenario.
    return n_defaults_per_scenario * portfolio.lgd * portfolio.ead_usd


def _norm_ppf(p: float) -> float:
    """Inverse standard-normal CDF; same Beasley-Springer-Moro approximation
    as the companion c11-irb-capital.py script. Inlined here to keep this
    script self-contained."""
    if not 0.0 < p < 1.0:
        raise ValueError("p must be in (0, 1)")
    a = [-3.969683028665376e1, 2.209460984245205e2, -2.759285104469687e2,
         1.383577518672690e2, -3.066479806614716e1, 2.506628277459239e0]
    b = [-5.447609879822406e1, 1.615858368580409e2, -1.556989798598866e2,
         6.680131188771972e1, -1.328068155288572e1]
    c = [-7.784894002430293e-3, -3.223964580411365e-1, -2.400758277161838e0,
         -2.549732539343734e0, 4.374664141464968e0, 2.938163982698783e0]
    d = [7.784695709041462e-3, 3.224671290700398e-1, 2.445134137142996e0,
         3.754408661907416e0]
    p_low, p_high = 0.02425, 1.0 - 0.02425
    if p < p_low:
        q = math.sqrt(-2.0 * math.log(p))
        return (((((c[0] * q + c[1]) * q + c[2]) * q + c[3]) * q + c[4]) * q + c[5]) \
            / ((((d[0] * q + d[1]) * q + d[2]) * q + d[3]) * q + 1.0)
    if p <= p_high:
        q = p - 0.5
        r = q * q
        return (((((a[0] * r + a[1]) * r + a[2]) * r + a[3]) * r + a[4]) * r + a[5]) * q \
            / (((((b[0] * r + b[1]) * r + b[2]) * r + b[3]) * r + b[4]) * r + 1.0)
    q = math.sqrt(-2.0 * math.log(1.0 - p))
    return -(((((c[0] * q + c[1]) * q + c[2]) * q + c[3]) * q + c[4]) * q + c[5]) \
        / ((((d[0] * q + d[1]) * q + d[2]) * q + d[3]) * q + 1.0)


def summarise(losses: np.ndarray, total_ead: float) -> dict[str, float]:
    """Compute the headline portfolio loss-distribution statistics."""
    return {
        "expected_loss": float(losses.mean()),
        "unexpected_loss": float(losses.std(ddof=1)),
        "var_95": float(np.quantile(losses, 0.95)),
        "var_99": float(np.quantile(losses, 0.99)),
        "var_999": float(np.quantile(losses, 0.999)),
        "es_99": float(losses[losses >= np.quantile(losses, 0.99)].mean()),
        "es_999": float(losses[losses >= np.quantile(losses, 0.999)].mean()),
        "max_loss": float(losses.max()),
        "max_loss_pct_ead": float(losses.max() / total_ead),
    }


def main() -> None:
    """Run the simulation at three correlation levels and report the headline."""
    base = HomogeneousPortfolio(
        n_obligors=100,
        pd=0.02,            # 2% per obligor
        lgd=0.45,
        ead_usd=1_000_000,  # $1M per obligor; $100M total
        rho=0.20,           # mid-range Basel-corporate-style correlation
    )
    n_scenarios = 10_000

    print("Stylised one-factor Monte Carlo credit-portfolio simulation")
    print("=" * 92)
    print(f"  Portfolio       : {base.n_obligors} identical obligors")
    print(f"  EAD per obligor : ${base.ead_usd:,.0f}   (total ${base.total_ead:,.0f})")
    print(f"  PD per obligor  : {base.pd * 100:.2f}%   LGD: {base.lgd * 100:.1f}%")
    print(f"  Scenarios       : {n_scenarios:,}")
    print()

    for rho in (0.05, 0.20, 0.50):
        port = HomogeneousPortfolio(
            n_obligors=base.n_obligors,
            pd=base.pd,
            lgd=base.lgd,
            ead_usd=base.ead_usd,
            rho=rho,
        )
        losses = simulate_portfolio_losses(port, n_scenarios=n_scenarios, seed=42)
        s = summarise(losses, port.total_ead)
        # Analytical EL for cross-check: EL = PD * LGD * total_EAD = 900,000.
        analytical_el = port.pd * port.lgd * port.total_ead
        print(f"  rho = {rho:>4.2f} ({'low' if rho < 0.1 else 'mid' if rho < 0.3 else 'high'} correlation)")
        print(f"    EL (simulated)        = ${s['expected_loss']:>12,.0f}   "
              f"(analytical: ${analytical_el:>10,.0f})")
        print(f"    UL (std dev)          = ${s['unexpected_loss']:>12,.0f}")
        print(f"    95%  Credit VaR       = ${s['var_95']:>12,.0f}")
        print(f"    99%  Credit VaR       = ${s['var_99']:>12,.0f}")
        print(f"    99.9% Credit VaR      = ${s['var_999']:>12,.0f}   "
              f"({s['var_999'] / s['expected_loss']:>4.1f}x EL)")
        print(f"    99%  Expected Shortfall = ${s['es_99']:>12,.0f}")
        print(f"    Worst scenario        = ${s['max_loss']:>12,.0f}   "
              f"({s['max_loss_pct_ead'] * 100:.1f}% of total EAD)")
        print()

    print("Observations:")
    print(" - The expected loss is essentially independent of rho (~$900K, the")
    print("   analytical PD * LGD * EAD): expectations do not depend on correlation.")
    print(" - The unexpected loss and the high-quantile VaRs grow sharply with rho:")
    print("   at rho = 0.05 the 99.9% VaR sits around 4-5x the EL, at rho = 0.50 it")
    print("   exceeds 15-20x the EL. The diversification benefit of imperfect")
    print("   correlation is the entire reason a portfolio's tail loss is not the")
    print("   sum of single-name tail losses.")
    print(" - The simulated EL reconciles to the analytical PD * LGD * EAD to within")
    print("   1-2% sampling noise across 10,000 scenarios; this is the standard")
    print("   reproducibility check on the simulator's correctness.")


if __name__ == "__main__":
    main()
